name: tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/tests.yml
      - CMakeLists.txt
      - pyproject.toml
      - roughpy_jax/**
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/tests.yml
      - CMakeLists.txt
      - pyproject.toml
      - roughpy_jax/**

concurrency:
  group: tests-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: ${{ matrix.os }}${{ matrix.arch_name && format(' ({0})', matrix.arch_name) || '' }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            arch_name: x86_64
          - os: windows-latest
            arch_name: AMD64
          - os: macos-14
            arch_name: arm64

    steps:
      - uses: actions/checkout@v6

      - uses: pypa/cibuildwheel@v3.2.1
        env:
          CIBW_ARCHS_LINUX: auto64
          CIBW_ARCHS_WINDOWS: auto64
          CIBW_ARCHS_MACOS: native
